/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Length.java
 *
 * Created on Jul 2, 2014, 3:05:14 AM
 */
package convertor;

/**
 *
 * @author Ayon
 */
public class Length extends javax.swing.JFrame {
    private String obj;
    private double obj1;
    private String obj2;
    private double res;
    private double res1;
    private double res2;
    private double res3;
    private double res4;
    private double res5;
    /** Creates new form Length */
    public Length() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("Length");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel3.setText("Unit");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "cm", "m", "km", "Feet", "Inches", "Miles" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel4.setText("Unit");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "cm", "m", "km", "Feet", "Inches", "Miles" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel5.setText("Amount");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel6.setText("Amount");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setText("Convert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_jTextField5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    obj = jComboBox3.getSelectedItem().toString();
        if(obj.equals("mm")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("mm")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("m")){
                res = obj1*0.001;
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("cm")){
                res1 = obj1*0.1;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("km")){
                res2 = obj1* 0.000001;
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("Miles")){
                res3 = obj1*(1/1609344);
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("Inches")){
                res4 = obj1*(1/25.4);
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("Feet")){
                res5= obj1*(1/304.8);
                jTextField6.setText(String.valueOf(res5));
            }
        }
     if(obj.equals("m")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("m")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("mm")){
                res = obj1*1000;
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("cm")){
                res1 = obj1*100;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("km")){
                res2 = obj1*(1/1000);
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("Miles")){
                res3 = obj1*(1/1609.344);
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("Inches")){
                res4 = obj1*39.37;
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("Feet")){
                res5 = obj1*3.280;
                jTextField6.setText(String.valueOf(res5));
            }
        }   
    if(obj.equals("cm")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("cm")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("m")){
                res = obj1*(1/100);
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("mm")){
                res1 = obj1*10;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("km")){
                res2 = obj1*(1/100000);
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("Miles")){
                res3 = obj1*(1/160934.4);
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("Inches")){
                res4 = obj1*(1/2.54);
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("Feet")){
                res4 = obj1*(1/30.48 );
                jTextField6.setText(String.valueOf(res4));
            }
        }    
     if(obj.equals("km")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("km")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("m")){
                res = obj1*1000;
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("cm")){
                res1 = obj1*100000;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("mm")){
                res2 = obj1*1000000;
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("Miles")){
                res3 = obj1*(1/1.609344);
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("Inches")){
                res4 = obj1*39370.07874 ;
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("Feet")){
                res5 = obj1* 3280.839895;
                jTextField6.setText(String.valueOf(res5));
            }
        }   
    if(obj.equals("Miles")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("Miles")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("m")){
                res = obj1*1609.344;
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("cm")){
                res1 = obj1*160934.4;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("km")){
                res2 = obj1*1.609344;
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("mm")){
                res3 = obj1* 1609344;
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("Inches")){
                res4 = obj1*6336;
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("Feet")){
                res4 = obj1*5280;
                jTextField6.setText(String.valueOf(res4));
            }
        }    
     if(obj.equals("Inches")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("Inches")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("m")){
                res = obj1*(1/39.37);
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("cm")){
                res1 = obj1*2.54;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("km")){
                res2 = obj1*0.0000254;
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("Miles")){
                res3 = obj1*(1/6336);
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("mm")){
                res4 = obj1* 25.4;
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("Feet")){
                res5 = obj1*(1/12);
                jTextField6.setText(String.valueOf(res5));
            }
        }   
   if(obj.equals("Feet")){
            obj1 = Double.parseDouble(jTextField5.getText());
            obj2 = jComboBox4.getSelectedItem().toString();
            if(obj2.equals("Feet")){
                jTextField6.setText(jTextField5.getText());
               }
            if(obj2.equals("m")){
                res = obj1*0.3048 ;
                jTextField6.setText(String.valueOf(res));
               }
            if(obj2.equals("cm")){
                res1 = obj1*30.48;
                jTextField6.setText(String.valueOf(res1));
               }
            if(obj2.equals("km")){
                res2 = obj1*0.0003048 ;
                jTextField6.setText(String.valueOf(res2));
               }    
            if(obj2.equals("Miles")){
                res3 = obj1*(1/5280);
                jTextField6.setText(String.valueOf(res3));
               }
            if(obj2.equals("Inches")){
                res4 = obj1*12;
                jTextField6.setText(String.valueOf(res4));
            }
            if(obj2.equals("mm")){
                res5 = obj1*304.8;
                jTextField6.setText(String.valueOf(res5));
            }
        }     
}//GEN-LAST:event_jButton2ActionPerformed

private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox4ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    dispose();
    list l = new list();
    l.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Length().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
